# Generated by Django 4.2 on 2024-04-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_exampletable_rental_listings"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(max_length=2048)),
                (
                    "rental_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="users.rental_listings",
                    ),
                ),
            ],
        ),
    ]
