# Generated by Django 4.2 on 2024-04-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingInfestationReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("building_id", models.IntegerField()),
                ("registration_id", models.IntegerField()),
                ("borough", models.CharField(max_length=100)),
                ("house_number", models.CharField(max_length=50)),
                ("street_name", models.CharField(max_length=255)),
                ("postcode", models.CharField(max_length=255)),
                ("dwelling_units", models.CharField(max_length=255)),
                ("infested_dwelling_unit_count", models.CharField(max_length=255)),
                ("eradicated_unit_count", models.CharField(max_length=255)),
                ("reinfested_dwelling_unit_count", models.CharField(max_length=255)),
                ("filing_date", models.DateField()),
                ("filing_period_start_date", models.DateField()),
                ("filing_period_end_date", models.DateField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("community_board", models.CharField(max_length=255)),
                ("council_district", models.CharField(max_length=255)),
                ("census_tract", models.CharField(max_length=50)),
                ("bin", models.CharField(max_length=255)),
                ("bbl", models.CharField(max_length=255)),
                ("nta", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleTable1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("example_column", models.CharField(max_length=255)),
            ],
        ),
    ]
