# Generated by Django 4.2 on 2024-04-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_buildinginfestationreport_exampletable1"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingViolation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("violation_id", models.IntegerField(unique=True)),
                ("building_id", models.IntegerField(default=0)),
                ("registration_id", models.CharField(default="", max_length=100)),
                ("boro_id", models.CharField(default="", max_length=100)),
                ("borough", models.CharField(default="", max_length=100)),
                ("house_number", models.CharField(default="", max_length=50)),
                ("low_house_number", models.CharField(default="", max_length=50)),
                ("high_house_number", models.CharField(default="", max_length=50)),
                ("street_name", models.CharField(default="", max_length=255)),
                ("street_code", models.CharField(default="", max_length=100)),
                ("postcode", models.CharField(default="", max_length=100)),
                ("apartment", models.CharField(default="", max_length=100)),
                ("story", models.CharField(default="", max_length=100)),
                ("block", models.CharField(default="", max_length=100)),
                ("inspection_date", models.DateField(default="2000-01-01")),
                ("approved_date", models.DateField(default="2000-01-01")),
                ("originalcertifybydate", models.DateField(default="2000-01-01")),
                ("originalcorrectbydate", models.DateField(default="2000-01-01")),
                ("ordernumber", models.CharField(default="", max_length=100)),
                ("nov_id", models.CharField(default="", max_length=100)),
                ("nov_issued_date", models.DateField(default="2000-01-01")),
                ("current_status_id", models.CharField(default="", max_length=100)),
                ("current_status", models.CharField(default="", max_length=100)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                ("community_board", models.CharField(default="", max_length=100)),
                ("council_district", models.CharField(default="", max_length=100)),
                ("census_tract", models.CharField(default="", max_length=100)),
                ("bin", models.CharField(default="", max_length=100)),
                ("bbl", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ExampleTable3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("example_column", models.CharField(max_length=255)),
            ],
        ),
    ]
