# Generated by Django 4.2 on 2024-04-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_buildingviolation_exampletable3"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceReport311",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_key", models.BigIntegerField(unique=True)),
                ("created_date", models.DateTimeField()),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                ("agency", models.CharField(max_length=50)),
                ("complaint_type", models.CharField(max_length=255)),
                (
                    "incident_zip",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "incident_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(max_length=50)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                (
                    "resolution_action_updated_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("community_board", models.CharField(max_length=50)),
                ("borough", models.CharField(max_length=100)),
                ("park_borough", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
