# Generated by Django 4.2 on 2024-04-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_servicereport311"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersHpdData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "users_rental_listings_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("most_recent_violation_date", models.DateField(blank=True, null=True)),
                ("count_violations", models.BigIntegerField(blank=True, null=True)),
                ("num_complaints", models.BigIntegerField(blank=True, null=True)),
                ("num_noise_complaints", models.BigIntegerField(blank=True, null=True)),
                ("most_recent_complaint", models.DateTimeField(blank=True, null=True)),
                (
                    "ttl_infested_apartments",
                    models.DecimalField(
                        blank=True, decimal_places=65535, max_digits=65535, null=True
                    ),
                ),
                ("last_bedbug_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "users_hpd_data",
                "managed": False,
            },
        ),
    ]
