# Generated by Django 4.2 on 2024-04-17 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_servicereport311"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersHpdData",
            fields=[
                (
                    "hpd",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hpd_data",
                        serialize=False,
                        to="users.rental_listings",
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("most_recent_violation_date", models.DateField(blank=True, null=True)),
                ("count_violations", models.BigIntegerField(blank=True, null=True)),
                ("num_complaints", models.BigIntegerField(blank=True, null=True)),
                ("num_noise_complaints", models.BigIntegerField(blank=True, null=True)),
                ("most_recent_complaint", models.DateTimeField(blank=True, null=True)),
                (
                    "ttl_infested_apartments",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=36, null=True
                    ),
                ),
                ("last_bedbug_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "users_hpd_data",
                "managed": False,
            },
        ),
    ]
