# Generated by Django 4.2 on 2024-04-16 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_usershpddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental_listings",
            name="users_rental_listings_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_listings",
                to="users.usershpddata",
            ),
        ),
    ]
