# Generated by Django 4.2 on 2024-04-16 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_rental_listings_users_rental_listings_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rental_listings",
            old_name="users_rental_listings_id",
            new_name="HPD",
        ),
    ]
