# Generated by Django 4.2 on 2024-04-16 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_rename_users_rental_listings_id_rental_listings_hpd"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rental_listings",
            old_name="HPD",
            new_name="HPD_id",
        ),
    ]
