# Generated by Django 4.2 on 2024-04-16 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_remove_rental_listings_hpd_id_rental_listings_hpd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rental_listings",
            name="HPD",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_listings",
                to="users.usershpddata",
            ),
        ),
    ]
