# Generated by Django 4.2 on 2024-04-16 23:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_alter_rental_listings_hpd"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usershpddata",
            options={},
        ),
    ]
