# Generated by Django 4.2 on 2024-04-16 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_usershpddata_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usershpddata",
            options={"managed": False},
        ),
    ]
