# Generated by Django 4.2 on 2024-04-16 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_rename_hpd_rental_listings_hpd"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rental_listings",
            name="hpd",
        ),
        migrations.AddField(
            model_name="rental_listings",
            name="hpd_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rental_listings",
                to="users.usershpddata",
            ),
        ),
    ]
