dist: jammy
language: python
matrix:
  include:
  - python: 3.11
install:
- pip install -r requirements.txt
before_script:
- python manage.py migrate
- python manage.py collectstatic --noinput
script:
- black .
- black --check .
- flake8 --ignore=E303,E501,W503,F401 --max-line-length=150
- coverage run --source=users manage.py test
after_success:
- coveralls
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: UabKcmaBFapLGCL4a1RdBtUFM5GewV5hxiK197jxZw3mxl81/F2KAozs7238z3pC63l1XBCGxO7XQzhSSKL1UU0aM8550SljCchQ7Dntya2P/YfZMSVFAN4KIW5eVLEbvDZaMQp+N3WZGcPghOkpHgz7TZY8v/iSQuVIDqxPhUycNTc7MI+UcS/IdY9t5h7ivpa2koXAF9JU3Qkyo+y3J+bk/2jcfXgn9Tpyc0URLum2TSrLpjk6smi/ZtlUdZEBc2RMBITMs0+QVp18zI2JMEnn/OHym8JonveIN362Ft5Pdo9q3NUtOF6JozLCSLQpNI74tTV3ajo/zrlQ/B8oNHQIA4IPP6biatNF1bCSTgNvO53tNBHB1oj6MyzODUOSWNErYmuh9U33PMi8O3LhV487ISC/3TJu+8br1MtxeMifMbtayPa5M/xf83sG5EnZHunxlXVWHuVex7jcadLYaFIL3ZPoNFHIKUWKZnVNcd9yZZnPzYQshYFK6S8i61ItOtJA7OsKNZmqV5hMYPohPnTXmkHjWeX4A3k5KyCyUlY/XkplDOfV/umnyBWaMW5auER9o2HMhtT0r7CSbEao2GUCSncOlDUBhewZ+CwnRaPTjEFQPD0/LpJZ6wXQ9DCLXTrtjs0lwizdo3YlWVgr0/OhunYHQHAhPtJ81IQQ3Xk=
  secret_access_key:
    secure: kTWgoQrOTqwFHUYo1kQuA/USNrHj7FQXEh0ETvAm1ZpxdvpKF3ocf17SmpSesIL492sACVPmAQ8oo9rGbjTwLAJ2yI7m50ILSgx0xWQdSqI4g5hdsNAYfjY1gqi2v7jMPg0jT4B3WxDOWljIvdbHotDmekjXiIYh4kHRLH9jx3q8H3frQh1bbpM75lCKnyQJrLrLfGDTv4ETsoClBj/RrZwJvbKI9gqZ6okXb1AFIhCA9XNvqeyDCnZLRiVlc2BBgd5RxC1ZMB2wvM9go4bH8zic+eNLVYBtTbISssfCujb1sl3PPKCBmO9kDUpIChipDvmGe/fugyYlH7YDxVVWiLlQBAPc3mtNtVVVmTa67+0ct9rjsCadUvdZp6ZU7Ww6x3TfNgrzpHMyj4Opla7RmZujRoAx3V8B/3rdgSehU2Fx3AS40ZctmgSd7wrDdu+ftzSZeXVd1p61ptU42cVGDA+UjSa4SkcPlZmp94tJa1jhMyz15oGB8CP0QuYnYjcoy+dEXrKUVA3tq18I0bM7SQMMRxQC0pWTKYkZudUDACCrSlTfR7vCrvUkihk79rNXQB8jH55RpriDm8sMojg80oz6UfzwpjL7O/GI+RN+dkVjcqTDKzQBCgwy2DUGjTnZw0lpuOTwEE9BSnYrRXnqvzJTF+Q7f9SpEtdkZIIMXMo=
  region: us-east-1
  app: rent_wise_nyc
  env: rent-wise-env
  bucket_name: $S3_BUCKET_NAME
  on:
    repo: gcivil-nyu-org/INET-Wednesday-Spring2024-Team-2
    branch: develop
  skip_cleanup: 'true'
env:
  global:
  - TEAM_2_DB_NAME: $TEAM_2_DB_NAME
  - TEAM_2_DB_USER: $TEAM_2_DB_USER
  - TEAM_2_DB_PW: $TEAM_2_DB_PW
  - TEAM_2_DB_HOST: $TEAM_2_DB_HOST
  - TEAM_2_DB_PORT: $TEAM_2_DB_PORT
  - COVERALLS_REPO_TOKEN: $COVERALLS_REPO_TOKEN